### ISSUE TITLE
nsqadmin: UPSTREAM_ERROR: Failed to query any nsqd

### ISSUE THREAD

**Issue by janbaer** [nsqio/nsq#1040]
I started to evaluate NSQ for our project. 

I tried to run the whole stack with **nqsd**, **msqlookupd** and **nsqadmin** within a Docker network with using Docker-compose. 

```
version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd 
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=127.0.0.1
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
```

With this configuration the **nsqadmin** worked correct.

Since my node-js test clients are not running within the same Docker network I had to change the broadcast address for **nsqd**. After this change I could send and read messages. 

But the **msqadmin** was showing me now the following error when I tried to open a channel or just show the count of processed messages.

```
UPSTREAM_ERROR: Failed to query any nsqd: Get http://127.0.0.1:4151/stats?format=json: dial tcp 127.0.0.1:4151: getsockopt: connection refused
```

What do I have to change to fix the problem? Can I use only nsqd and nsqadmin together without nsqlookupd? I tried to configure **nsqd-http-addres** instead of **lookupd-http-address** but it won't work.

One more question for my understandings. To not have a SPOF I should use more than one NSQD instances. NSQLOOKUPD is helping the consumer to get all messages for the topic to my channel independent to which NSQD instance the message was sent. But the producer has to decide to which NSQD instance he has to connect and to this instance the messages will be send. In case that this instance will have a problem, the producer has to reconnect to another NSQD instance. So the producer has to know all addresses of all running NSQD instances to prevent the SPOF problem. Did I understand it right? Thanks for the help with my Docker problem and also for the clarification in advance.

**Comment by ploxiln** [comment]
Container network links make this more complicated. It is possible to do it that way, but we won't help you ;)

It's simpler to think of it server-by-server. You can put an nsqd on each server which has any services that publish messages, and always publish to localhost nsqd. https://nsq.io/deployment/topology_patterns.html#distributed-systems

It's not intended to use nsqlookupd to find which hosts to publish to. You could specify a list of nsqd addresses to publish to, a sort of "central cluster". But you wouldn't use nsqlookupd for this, and nsqd client libraries are not as sophisticated when publishing to multiple nsqd, they typically just do round-robin.

**Comment by ploxiln** [comment]
(nsqlookupd is intended just for consumers to find nsqd, and for nsqadmin, but not for producers.)

**Comment by mreiferson** [comment]
I _think_ the broadcast address should be set to the IP address of the container running `nsqd` (itself, essentially), I'm not sure how to do that specifically with docker compose.

**Comment by janbaer** [comment]
@mreiferson Thanks, will try it.

@ploxiln @mreiferson With PRODUCER I meant the client that will create the message that another client will consume some later. So what I understand is, that the client which want's to consume the message don't need to know to which NSQD instance the message was sent since NSQLOOKUPD will fnd this out for the consumer. But how about the client which is creating the message. So this client has to know the address of any NSQD instance to push the message. And in case that this NSQD instance is down it has to connect to another NSQD instance. Is this correct? So in best case I could maybe use a load balancer before two or more NSQD instances to have the responsibility to switch between the NSQD instance not on the client (the producer) side. I just ask about it, since in all presentations I saw always about how to prevent the SPOF scenario for the consumer client. But how about the producer client? Thanks in advance for the clarification!

**Comment by ploxiln** [comment]
A load balancer for pub via http to a central cluster of nsqd would work.

In the "publish to localhost" setup/topology, we just assume that the nsqd running on localhost will always be reachable, or otherwise this server is not running or getting traffic anyway. nsqd does not really guarantee that every message will be published and won't be lost - the typical "no SPoF" setup instead guarantees that messages on other servers will keep flowing (without any significant slowdown) when some servers "go down". (If those servers just had a temporary network problem, their messages will just be delayed. If they crashed hard, it is likely that many messages produced on those servers are lost.)

**Comment by JoseFMP** [comment]
Any news on this issue? is affecting me.

**Comment by euskadi31** [comment]
ping

**Comment by MarksGui** [comment]
--broadcast-address=host.docker.internal

**Comment by jvaca92** [comment]
In Kubernetes enviroment I have setup the attribute **--broadcast-address** with name which I have used for **nsqd**  service.

**Comment by obedtandadjaja** [comment]
Got it working by specifying the nsqd `container_name` in `--broadcast-address`. See my configuration below:

```
  nsqlookupd:
    container_name: nsqlookupd
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"

  nsqd:
    container_name: nsqd
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=nsqd
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"

  nsqadmin:
    container_name: nsqadmin
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171"
```
