### ISSUE TITLE
trying to use nsq inside docker- nsqjs reader does not receive messages. Everything is ok with nsq running locally

### ISSUE THREAD

**Issue by triesa** [nsqio/nsq#1087]
I cant understand which ports and host should i specify in place where i posting messages and where i listen for them?
I followed the documentation
```version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --broadcast-address=nsqlookupd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171"
```
the only thing i have added is --broadcast-address=nsqlookupd  - i dont know is it right or not?
I am using nodejs locally and nsq in docker.
Previously i have used nsq locally and everything is worked fine
i just started the nsqlookupd with simple `nsqlookupd` and nsqd with `nsqd --broadcast-address=127.0.0.1 --lookupd-tcp-address=127.0.0.1:4160`.

After all in my nodejs i send messages like this

```  return request
    .post('http://localhost:4151/pub?topic=cool_event')
    .send(data)
```

and in other node.js process where is nsqjs reader sat up i have
```const nsq = require('nsqjs');
const reader = new nsq.Reader('cool_event', 'cool_event_channel', {
  lookupdHTTPAddresses: '127.0.0.1:4161',
});

reader.connect();
reader.on('message', function (msg) {
```

And everything worked- i receive messages in reader. 

But for now with nsq inside docker i cant figure out which  host and ports should i specify in message post, and which in reader

```
docker-compose ps
            Name                          Command               State                                            Ports                                          
----------------------------------------------------------------------------------------------------------------------------------------------------------------
proj_nsqadmin_1     /nsqadmin --lookupd-http-a ...   Up      4150/tcp, 4151/tcp, 4160/tcp, 4161/tcp, 4170/tcp, 0.0.0.0:32770->4171/tcp               
proj_nsqd_1         /nsqd --broadcast-address= ...   Up      0.0.0.0:32774->4150/tcp, 0.0.0.0:32773->4151/tcp, 4160/tcp, 4161/tcp, 4170/tcp, 4171/tcp
proj_nsqlookupd_1   /nsqlookupd                      Up      4150/tcp, 4151/tcp, 0.0.0.0:32769->4160/tcp, 0.0.0.0:32768->4161/tcp, 4170/tcp, 4171/tcp
```

**Comment by dudleycarr** [comment]
@triesa There are two things getting in the way of this working. First, since you're using nsqjs locally (not within Docker), you need to expose `nsqd` and `nsqlookupd` locally. `docker-compose ps` tells you that the ports are exposed, but on random ports as opposed to ports `4150`, `4151`, or `4161` for the various services. 

The other issue is related to the broadcast address. I'd recommend you create an entry in your /etc/hosts file for `nsqd` to point to 127.0.0.1. 

Here's what your config should look like, I think:
```yaml
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
```
