### ISSUE TITLE
How to set the broadcast-address of the nsqd , when deployed multiple nsqd on the docker swarm

### ISSUE THREAD

**Issue by guanwenbogit** [nsqio/nsq#1173]
I met some trouble when I deploy the nsq cluster on the docker swarm
Well, there are 3 instances in the swarm. 
192.168.99.100
192.168.99.101
192.168.99.102

Then I docker stack deploy with the compose file like this:
```
version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    deploy:
      mode: global
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
```
If I didn't set the broadcast-address for the nsqd, it would be set default with host name.
The response from the nsqlookupd/lookup interface like this:
```
{"channels":["tony"],"producers":[{"remote_address":"10.0.0.10:52210","hostname":"5adf2bdbbe78","broadcast_address":"5adf2bdbbe78","tcp_port":4150,"http_port":4151,"version":"1.1.0"}]}

```

However, the consumer which is outside of the swarm , can not connect the using the function ConnectToNSQLookupd("192.168.99.100:4161"). Because, the broadcast-address is 
5adf2bdbbe78. The consumer can't the parse the hostname to an IP-Address. 
Badly, I can not set broadcast-address to the nsqds in the compose-file respectively, like 192.168.99.100,192.168.99.101,192.168.99.102 which are can connected by outside consumer. 

Do you have some suggestion for this situation?
Otherwise, may I have to put the consumers into the swarm with the same network or do the docker run manually one by one with broadcast-address setting on my instances?
