### ISSUE TITLE
Deny public access

### ISSUE THREAD

**Issue by sujeshthekkepatt** [nsqio/nsq#1176]
My app runs on GAE flexible environment. I have queue service(NSQ) running on a VM instance on the same project. Currently, both are connected using the IP address of the VM for service discovery and publishing messages. The necessary ports are also exposed to the public. Is there any way I can override this and connect internally like using a local IP address? So that I can remove this exposure? Any help appreciated

**Comment by ploxiln** [comment]
nsqd and friends are typically run on servers behind a firewall. One common way is using AWS ec2 security groups: allow your ec2 instances, possibly in one or more security groups, to access each other on ports 4150, 4151, 4160, 4161 for nsqd/nsqlookupd, but only allow ports 80, 443 from the outside world to your web-serving instances.

If you have just one server, you could instead use localhost for everything. Have nsqd use `--http-address=128.0.0.1:4151` and `--tcp-address=127.0.0.1:4150`. With just one server you could skip nsqlookupd. If using nsqlookupd for testing or mirroring another environment you could set nsqd `--broadcast-address=localhost` or something like that. This is admittedly not a generally useful topology :)

If you have separate network interfaces for internal and public network, you could have nsqd listen only on the internal network address, with the above mentioned options. But that's not too common. You probably need to use a firewall of some kind (whether it's called "security groups" or something else, or manually with iptables) to allow connections only from your own servers.

There's also optional tls, tls client certificate checks, and an auth protocol that allows you to set up another service to check passwords from connecting clients, but this is pretty complicated stuff, usually not a good place to start.

**Comment by sujeshthekkepatt** [comment]
```

version: "2"
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    restart: always
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=public_ip_Address
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    restart: always
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "80:4171"
    restart: always



```

This is the docker-compose file I have been using. The app instance runs on a google application engine(flexible environment). Is there a way that I could remove public IP address to it's local internal IP. The nsq lives on a separate VM instance inside the same project. The reader and writer use the internal IP address. But for broadcast ip address it won't work. Since the ports are open anyone can access it. Since blocking admin interfaces will not make any good. Is there something I can do from nsq? Or any recommendation for the architecture. I run single server for nsq
