### ISSUE TITLE
How to make nsq works in docker

### ISSUE THREAD

**Issue by lancemenz** [nsqio/nsq#1258]
this is my docker-compose.yaml

```
version: "3"

services: 
  nsq-lookupd:
    image: nsqio/nsq:v1.2.0
    container_name: nsq-lookupd
    ports: 
      - 4160:4160
      - 4161:4161
    command: /nsqlookupd 

  nsq-nsqd:
    image: nsqio/nsq:v1.2.0
    container_name: nsq-nsqd
    volumes:
      - ./nsq/data:/data 
    ports: 
      - 4150:4150
      - 4151:4151
    depends_on: 
      - nsq-lookupd
    links: 
      - nsq-lookupd
    command: /nsqd -data-path=/data -lookupd-tcp-address=nsq-lookupd:4160 -broadcast-address=nsq-nsqd -max-msg-size=10485760

  nsq-admin:
    image: nsqio/nsq:v1.2.0
    container_name: nsq-admin
    ports: 
      - 4171:4171
    depends_on: 
        - nsq-lookupd
    links: 
      - nsq-lookupd
      - nsq-nsqd
    command: /nsqadmin -lookupd-http-address=nsq-lookupd:4161 
```

after running ```docker-compose up``` , I can access the web ui from ```http://127.0.0.1:4171/```
It looked normal, but when I tried to create a topic & channel, then access the channel, it always gave the error like below

![image](https://user-images.githubusercontent.com/63644907/83616175-18651800-a5ba-11ea-8842-9ebb61dc1728.png)

![image](https://user-images.githubusercontent.com/63644907/83616212-22871680-a5ba-11ea-960b-cad54b102e54.png)

the error log like below 
![image](https://user-images.githubusercontent.com/63644907/83616440-6d089300-a5ba-11ea-8af6-7a3d7de79960.png)

it's kind of weird, I have tested the network between nsq-nsqd, nsq-admin,nsq-lookupd, using ping in the 3 containers, the network works well.

and also, from the log, it has accessed nsq-nsqd successfully before the failure at the line 
```
nsq-nsqd       | [nsqd] 2020/06/03 08:50:16.815028 INFO: 200 GET /stats?format=json&include_clients=false (172.20.0.4:42692) 191.1µs
```
so I'm confused why it always fails when I'm trying to access the channel. 

I also tried to run nsq on my Mac, it works well, below is my command to run nsq directly on Mac

```
nohup ./nsqlookupd > /dev/null 2>&1 &
nohup ./nsqd --lookupd-tcp-address=127.0.0.1:4160 -broadcast-address=127.0.0.1 -max-msg-size=10485760 > /dev/null 2>&1 &
nohup ./nsqadmin --lookupd-http-address=127.0.0.1:4161 > /dev/null 2>&1 &
```

I just want to make nsq works in docker, that will be much more convenient for my system building, thanks
