### ISSUE TITLE
*: official helm chart

### ISSUE THREAD

**Issue by LordNoteworthy** [nsqio/nsq#1315]
Hello,

There are few helm charts floating around about NSQ. I was wondering if this organization would be interested to create an official one, probably not in this git repo.

We can start with what I have been using so far, then the k8s and helm experts could help improve it.

Cheers.

**Comment by jehiah** [comment]
@LordNoteworthy I am interested in this area, but am not very familiar with helm at the moment. Can you link to the configuration you are using, and describe a little about how you ended up on that configuration?

**Comment by LordNoteworthy** [comment]
@jehiah 

[Here ](https://github.com/saferwall/saferwall/tree/master/deployments/saferwall/charts/nsq) is the helm chart which I am currently using. I took the same chart that [emailcourt](https://github.com/emaincourt) was trying to submit to the helm chart repository some time ago: [PR](https://github.com/helm/charts/pull/8707), it was never merged unfortunately.

The reason why I am using Helm is just because we deploy everything inside a Kubernetes cluster and it make it easy to manage dependencies.

Here is my current config of the chart:
```yaml
nsq:
  enabled: true
  nsqd:
    name: nsqd
    replicaCount: 3
    persistence:
      storageClass: "default"
      resources:
        requests:
          storage: 1Gi
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
  nsqlookupd:
    name: nsqlookupd
    replicaCount: 2
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
  nsqadmin:
    name: "admin"
    autoscaling:
      enabled: false
    replicaCount: 1
    resources:
        limits:
          cpu: 1000m
          memory: 2Gi
```

We can start by first adding nsqd and nsqlookupd as `statefulset` and `nsqadmin` as a deployment + services of each of those. Then we can start extending the chart with PodDisruptionBudget, etc ...

My understanding of Kubernetes as a whole is pretty humble, I would love feedback's from the experts.

**Comment by LordNoteworthy** [comment]
Shall I submit a PR ? I can create a new folder in the root folder called `helm`.

**Comment by dselivanov** [comment]
Poking @bezero - any chance we can contribute?

**Comment by bezero** [comment]
@dselivanov  [helm/charts](https://github.com/helm/charts) is no longer supported. The [PR](https://github.com/emaincourt/charts/tree/incubator/nsq-chart/incubator/nsq) created by [emaincourt](https://github.com/emaincourt) works fine. You can modify [templates/nsqadmin-hpa.yaml](https://github.com/emaincourt/charts/blob/incubator/nsq-chart/incubator/nsq/templates/nsqadmin-hpa.yaml) as follows:
```yaml
# tested on k8s v1.17.9
{{- if and (.Values.nsqadmin.enabled) (.Values.nsqadmin.autoscaling.enabled) }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nsq.nsqadmin.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nsq.name" . }}
    helm.sh/chart: {{ include "nsq.chart" . }}
    app.kubernetes.io/component: {{ .Values.nsqadmin.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.nsqadmin.autoscaling.annotations }}
  annotations:
{{ toYaml . | trim | indent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nsq.nsqadmin.fullname" . }}
  minReplicas: {{ .Values.nsqadmin.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.nsqadmin.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.nsqadmin.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.nsqadmin.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
```
I gues, if you would like to create an officially supported charts you can start with this PR and add any missing requirements. If needed I would gladly help with updating charts.
