### ISSUE TITLE
nsqadmin: graphite integration not show statsd counter

### ISSUE THREAD

**Issue by sykrabadi** [nsqio/nsq#1430]
Hello,

I'm running the nsqadmin with graphite integrated in order to unlock the rate feature. The `depth`, `in-flight`, `deffered`, and `connection `graph are showed up, meanwhile the `messages`, `requested`, timeout, and rate `don't`. 

This is the `docker-compose` file that I use to run nsq and graphite
```yaml
version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    container_name: nsqlookupd
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    container_name: nsqd
    command: /nsqd --broadcast-address=nsqd --statsd-address=graphite:8125 --data-path=/data --lookupd-tcp-address=nsqlookupd:4160 --statsd-interval=0m45s
    volumes:
      - /data
    depends_on:
      - nsqlookupd
      - graphite
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    container_name: nsqadmin
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161 --proxy-graphite=true --graphite-url=http://graphite --statsd-interval=0m45s 
    depends_on:
      - nsqlookupd
      - nsqd
      - graphite
    ports:
      - "4171:4171"
  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-3
    container_name: graphite
    ports:
      - 80:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
```

Here is the full picture from nsqadmin.

![Screenshot 2022-10-29 105804](https://user-images.githubusercontent.com/64145699/198812810-69d810f8-f1ea-4fcc-ab61-8e918094666a.png)

Moreover, I also added the additional configuration for graphite as mentioned here [https://nsq.io/components/nsqd.html#statsd--graphite-integration](https://nsq.io/components/nsqd.html#statsd--graphite-integration). Here is the screenshot taken from graphite container for additional config on `storage-schemas.conf` and `storage-aggregation.conf` files.

![Screenshot 2022-10-29 110250](https://user-images.githubusercontent.com/64145699/198812998-8f001412-474d-4a0f-8df4-762ab10d2259.png)

![Screenshot 2022-10-29 110230](https://user-images.githubusercontent.com/64145699/198813001-d6f0f625-4cd3-439c-a6fe-482700dc09cc.png)

Here is the screenshot taken from graphite browser. The `gauge` folder showed up, meanwhile the `counter` folder doesn't.

![Screenshot 2022-10-29 110425](https://user-images.githubusercontent.com/64145699/198813060-a77392e3-4754-4ef9-b3f5-26d88ed093b1.png)

Is there any configuration that I missed so that the `rate` etc doesn't show up in the nsqadmin?

Thank you for the assists!
