### ISSUE TITLE
Refresh Docker image

### ISSUE THREAD

**Issue by janbaer** [nsqio/nsq#1471]
Trivy is reporting us for the current version 1.21 of the Docker image 3 critical security issues.

```yaml
  - fixedVersion: 1.1.1l-r0
    installedVersion: 1.1.1k-r0
    lastModifiedDate: "2022-12-06T21:23:00Z"
    links: []
    primaryLink: https://avd.aquasec.com/nvd/cve-2021-3711
    publishedDate: "2021-08-24T15:15:00Z"
    resource: libcrypto1.1
    score: 9.8
    severity: CRITICAL
    target: ""
    title: SM2 Decryption Buffer Overflow
    vulnerabilityID: CVE-2021-3711
  - fixedVersion: 1.1.1l-r0
    installedVersion: 1.1.1k-r0
    lastModifiedDate: "2022-12-06T21:23:00Z"
    links: []
    primaryLink: https://avd.aquasec.com/nvd/cve-2021-3711
    publishedDate: "2021-08-24T15:15:00Z"
    resource: libssl1.1
    score: 9.8
    severity: CRITICAL
    target: ""
    title: SM2 Decryption Buffer Overflow
    vulnerabilityID: CVE-2021-3711
    vulnerabilityID: CVE-2022-28391
  - fixedVersion: 1.2.12-r2
    installedVersion: 1.2.11-r3
    lastModifiedDate: "2023-07-19T00:56:00Z"
    links: []
    primaryLink: https://avd.aquasec.com/nvd/cve-2022-37434
    publishedDate: "2022-08-05T07:15:00Z"
    resource: zlib
    score: 9.8
    severity: CRITICAL
    target: ""
    title: heap-based buffer over-read 
```

Since the Dockerfile is using the base image `alpine:latest`, a simple rebuild of the Docker image would fix the issue, because the latest version of the alpine image has fixed all critical and also as high rated security issues.
