### ISSUE TITLE
use docker swarm install nsq,why nsqd always "exiting messagePump" + "failed to read command - read tcp 10.0.2.180:4150->10.0.2.41:44052: read: connection reset by peer" ?

### ISSUE THREAD

**Issue by opvexe** [nsqio/nsq#1501]
```
version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    restart: always
    command: /nsqlookupd
    deploy:
      replicas: 1
    networks:
      - my_overlay_network

  nsqd:
    image: nsqio/nsq
    restart: always
    volumes:
      - /mnt/nsqio/data:/data
    command: >
      /nsqd
      -data-path=/data
      --lookupd-tcp-address=pcc_plugin_nsqlookupd:4160
      --max-msg-size=5242880
      --mem-queue-size=10000
    depends_on:
      - nsqlookupd
      - nsq-auth
    deploy:
      replicas: 1
    networks:
      - my_overlay_network

  nsqadmin:
    image: nsqio/nsq
    restart: always
    command: /nsqadmin --lookupd-http-address=pcc_plugin_nsqlookupd:4161
    depends_on:
      - nsqlookupd
    deploy:
      replicas: 1
    networks:
      - my_overlay_network

networks:
  my_overlay_network:
    external: true
```

Error:

```
failed to read command - read tcp 10.0.2.180:4150->10.0.2.41:44052: read: connection reset by peer
```
