### ISSUE TITLE
docs: docker compose config for running nsqd, nsqlookupd, and nsqadmin

### ISSUE THREAD

**Issue by mingfang** [nsqio/nsq#516]
Here is a fig.yml that can run the entire nsq stack easily for demo and evaluation.
Make sure to plugin your real <host>

```
nsqlookupd:
  image: nsqio/nsqlookupd
  ports:
    - "4160:4160"
    - "4161:4161"
  command: -broadcast-address=<host>

nsqd:
  image: nsqio/nsqd
  ports:
    - "4150:4150"
    - "4151:4151"
  command: -broadcast-address=<host>  -lookupd-tcp-address=<host>:4160

nsqadmin:
  image: nsqio/nsqadmin
  ports:
    - "4171:4171"
  command: -lookupd-http-address=<host>:4161
```
