### ISSUE TITLE
Question: How do we `aws-beanstalk` the way we `docker-compose` for nsq?

### ISSUE THREAD

**Issue by roylee0704** [nsqio/nsq#790]
In `docker-compose.yml`. It's really easy to set up links between nsq applications: nsqdlookd, nsqd, etc.

```yml
version: "2"
services: 
    nsqlookupd:
        image: nsqio/nsq 
        ports:
            - "4160:4160"
            - "4161:4161"
        command: /nsqlookupd
    
    nsqd:
        image: nsqio/nsq
        ports:
            - "4150"
            - "4151"
        links:
            - nsqlookupd:nsqlookupd
        command: /nsqd --lookupd-tcp-address=nsqlookupd:4160

    nsqdadmin:
        image: nsqio/nsq 
        ports:
            - "4171:4171"
        links:
            - nsqlookupd:nsqlookupd
        command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
```

But what about in `dockerrun.aws.json`? Does anyone have any experience in that?
