### ISSUE TITLE
nsqd nslookupd ping errors

### ISSUE THREAD

**Issue by chacken** [nsqio/nsq#804]
It should be noted that nsqadmin works, but it takes a really long time (30 seconds?) for it to load the nodes, topics, pages, and there aren't any nodes displaying.. I assume because of the issue below.
"NSQd Nodes (0)"

So first and foremost, I know nsqlookupd works because running
curl http://{host_ip}:4161/ping
returns a 200
```
nsqlookupd_1  | [nsqlookupd] 2016/11/02 18:22:10.899227 200 GET /ping (104.198.250.26:60746) 870ns
nsqlookupd_1  | [nsqlookupd] 2016/11/02 18:22:12.280844 200 GET /ping (104.198.250.26:60776) 820ns
nsqlookupd_1  | [nsqlookupd] 2016/11/02 18:22:12.898527 200 GET /ping (104.198.250.26:60794) 990ns
nsqlookupd_1  | [nsqlookupd] 2016/11/02 18:22:13.361662 200 GET /ping (104.198.250.26:60806) 894ns
nsqlookupd_1  | [nsqlookupd] 2016/11/02 18:22:13.809804 200 GET /ping (104.198.250.26:60820) 650ns
```
pinging nsqd also returns a 200
```
nsqd_1        | [nsqd] 2016/11/02 18:24:37.702945 200 GET /ping (104.198.250.26:48674) 2.077µs
nsqd_1        | [nsqd] 2016/11/02 18:24:39.991282 200 GET /ping (104.198.250.26:48752) 1.457µs
nsqd_1        | [nsqd] 2016/11/02 18:24:40.462521 200 GET /ping (104.198.250.26:48768) 1.55µs
nsqd_1        | [nsqd] 2016/11/02 18:24:40.857580 200 GET /ping (104.198.250.26:48780) 1.42µs
nsqd_1        | [nsqd] 2016/11/02 18:24:41.196890 200 GET /ping (104.198.250.26:48798) 1.453µs
nsqd_1        | [nsqd] 2016/11/02 18:24:41.542874 200 GET /ping (104.198.250.26:48812) 1.413µs
```

However, it seems something isn't right when nsqd tries to connect to nsqlookupd.

```
nsqd_1        | [nsqd] 2016/11/02 18:22:18.920595 LOOKUPD(nsqlookupd:4161): sending heartbeat
nsqd_1        | [nsqd] 2016/11/02 18:22:18.920622 LOOKUP connecting to nsqlookupd:4161
nsqd_1        | [nsqd] 2016/11/02 18:22:18.921464 LOOKUPD(nsqlookupd:4161): ERROR IDENTIFY - write tcp 172.17.0.4:41156->172.17.0.2:4161: write: broken pipe
nsqd_1        | [nsqd] 2016/11/02 18:22:18.921499 LOOKUPD(nsqlookupd:4161): ERROR PING - write tcp 172.17.0.4:41156->172.17.0.2:4161: use of closed network connection
nsqd_1        | [nsqd] 2016/11/02 18:22:33.920663 LOOKUPD(nsqlookupd:4161): sending heartbeat
nsqd_1        | [nsqd] 2016/11/02 18:22:33.920692 LOOKUP connecting to nsqlookupd:4161
nsqd_1        | [nsqd] 2016/11/02 18:22:33.921447 LOOKUPD(nsqlookupd:4161): ERROR IDENTIFY - response body size (1213486160) is greater than limit (5242880)
nsqd_1        | [nsqd] 2016/11/02 18:22:33.921486 LOOKUPD(nsqlookupd:4161): ERROR PING - write tcp 172.17.0.4:41157->172.17.0.2:4161: use of closed network connection
```

I realize I can change  -max-body-size=5123840 to a larger value, but I'm not even sending messages at this point, it's just pinging, so I have no idea why the response body size is so large.

Here is my docker-compose file:
```
nsqlookupd:
  image: nsqio/nsq
  command: /nsqlookupd
  ports:
    - "4160:4160"
    - "4161:4161"
nsqd:
  image: nsqio/nsq
  command: /nsqd --lookupd-tcp-address=nsqlookupd:4161
  links:
    - nsqlookupd:nsqlookupd
  ports:
    - "4150:4150"
    - "4151:4151"
nsqadmin:
  image: nsqio/nsq
  command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
  links:
    - nsqlookupd:nsqlookupd
  ports:
    - "4171:4171"
```
