### ISSUE TITLE
docker: Problem with 127.0.0.1 as nsqd broadcast 

### ISSUE THREAD

**Issue by lifeRockss** [nsqio/nsq#966]
Hi,
I am raising this issue again as the workaround isn't suitable for deployment.
I get an error when clicked on the node (127.0.0.1) if the broadcast-address=127.0.0.1 is used.
Following is my docker compose file

```yml
version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160   --broadcast-address=127.0.0.1
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
```

Everything works fine (like posting message and receiving it) only issue is when I navigate to http://localhost:4171/nodes and click on the value of broadcast-address (127.0.0.1) I get the error. as attached.
 
![screen shot 2017-11-24 at 12 38 53- 24 nov 2017](https://user-images.githubusercontent.com/15776055/33211519-dbe51486-d116-11e7-9630-4d17623a8fd5.png)

![screen shot 2017-11-24 at 12 39 00- 24 nov 2017](https://user-images.githubusercontent.com/15776055/33211526-e0fd06d6-d116-11e7-9ff9-92c06b8f47d8.png)
