### ISSUE TITLE
nsqadmin -- ERROR: failed to decode JSON - Unexpected token in JSON at position 152

### ISSUE THREAD

**Issue by nmiculinic** [nsqio/nsq#997]
I'm having issues with accessing nsqadmin in the k8s cloud.
This is kubernetes helm chart: https://pastebin.com/WzjLnKs2
Values are:
```
nsq:
  image: nsqio/nsq
  tag: v1.0.0-compat
  lookupd:
    replicas: 3
  admin:
    replicas: 2
```

And I'm accessing nsqadmin via:
```kubectl port-forward nsqadmin-6db475c485-82pkv 4900:4171```

```localhost:4900```

I can see all topics clearly, but if I click on some topic or on the counter the following error appears:
```ERROR: failed to decode JSON - Unexpected token in JSON at position 152```
for http://localhost:4900/counter
